[flake8]
# Set to 120 instead of 100 because black sometimes creates longer lines
max-line-length = 120
extend-ignore =
    # See https://github.com/PyCQA/pycodestyle/issues/373
    E203,

[tool:pytest]
doctest_optionflags = NORMALIZE_WHITESPACE
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session 
filterwarnings =
    error
    # Triggered by dateutil for Python 3.12
    ignore:.*Use timezone-aware objects to represent datetime:DeprecationWarning:dateutil
    # The following warnings are triggered by dask
    ignore:unclosed <socket:ResourceWarning
    ignore:unclosed event loop:ResourceWarning
    ignore:unclosed context:ResourceWarning
    ignore:.*Port .* is already in use:UserWarning:distributed
    ignore:Creating .*directories is taking .*time:UserWarning:distributed
    ignore:Couldn't detect .* IP address .* [Errno 51] .* unreachable:RuntimeWarning:distributed
    ignore:The --rsyncdir command line argument and rsyncdirs config variable are deprecated.
    # Triggered after upgrading to pytest 8.4.0 
    # Seems to be an interaction with cover. Only fails when running with coverage.
    # See https://github.com/pytest-dev/pytest-cov/issues/694 and related issue
    ignore:unclosed database in <sqlite3.Connection
testpaths = tests
norecursedirs =
    integration
    testdata
    tests/pytest_helper
    .ropeproject
    pharmpy/reporting/jupyter_sphinx

python_files = test_*.py
addopts =
    -ra
    --strict-markers
    --doctest-modules
    --doctest-glob=\*.rst
    --tb=short

[darglint2]
ignore=DAR401,DAR402
